version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    env_file:
      - .env

  postgres:
    image: postgres
    container_name: postgres
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - ./db/data:/var/lib/postgresql/data

  auth:
    build:
      context: ./
      dockerfile: ./apps/auth/Dockerfile
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - postgres
    ports:
      - '3000:3000'

  api:
    build:
      context: ./
      dockerfile: ./apps/api/Dockerfile
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - auth
      - presence
    ports:
      - '4000:5000'

  presence:
    build:
      context: ./
      dockerfile: ./apps/presence/Dockerfile
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - postgres
    ports:
      - '1000:1000'

  # chat:
  #   build:
  #     context: ./
  #     dockerfile: ./apps/chat/Dockerfile
  #   env_file:
  #     - .env
  #   depends_on:
  #     - rabbitmq
  #   ports:
  #     - '2000:2000'
